### ISSUE TITLE
Lines don't clear when switching between projects.

### ISSUE THREAD

**Issue by blake-azzuu** [u1055376Ash/Group-Project#11]
When switching between projects the lines between classes are not disposed.

**Comment by u1055376Ash** [comment]
I cant seem to replicate this, at least not today :S

**Comment by blake-azzuu** [comment]
Attached a screenshot to show the problem. 
![578551f3fc5e9d46eb6be27fc05cb8fc](https://cloud.githubusercontent.com/assets/501815/6772159/a247a64c-d0ee-11e4-8d5f-13bc37ca1b89.png)
![324c2baaad9a79841b4d0a88217af873](https://cloud.githubusercontent.com/assets/501815/6772160/a39ff5a8-d0ee-11e4-90ee-9f33d6210b40.png)

**Comment by u1055376Ash** [comment]
This has been fixed now :smile:
